# These are supported funding model platforms

github: rafasoares 
patreon: rafasoares
ko_fi: rafasoares
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
liberapay: rafasoares
issuehunt: rafasoares
